blog/web/views.py
from flask import request, render_template, Blueprint, redirect, url_for

# 编码解码
from back.models import Article, ArticleType

web_blue = Blueprint('web', __name__)


# 跳转主页
@web_blue.route('/', methods=['GET'])
def blog():
    return render_template('web/index.html')


# 主页
@web_blue.route('/blog_index/', methods=['GET', 'POST'])
def blog_index():
    articles = Article.query.limit(10).all()
    return render_template('web/index.html', articles=articles)


# 博客日记
@web_blue.route('/blog_diary/', methods=['GET', 'POST'])
def blog_diary():
    article = ArticleType.query.limit(10).all()
    articles = Article.query.limit(10).all()
    return render_template('web/list.html', article=article, articles=articles)


# 优秀个人博客
@web_blue.route('/blog_good/', methods=['GET', 'POST'])
def blog_good():
    if request.method == 'GET':
        return render_template('web/daohang.html')


# 关于我
@web_blue.route('/blog_about/', methods=['GET', 'POST'])
def blog_about():
    if request.method == 'GET':
        return render_template('web/about.html')


# 添加文章
@web_blue.route('/return_back/', methods=['GET', 'POST'])
def return_back():
    return redirect(url_for('back.admin_login'))


# 内容
@web_blue.route('/blog_content/<int:id>/', methods=['GET', 'POST'])
def blog_content(id):
    if request.method == 'GET':
        # 标签云 取标签id
        article = ArticleType.query.limit(10).all()
        # 通过标签 取对应id文章内容
        content_id = Article.query.filter_by(id=id).first()
        # 点击排名 文章显示
        articles = Article.query.limit(10).all()
        # 通过id 取 > id值 的第一个文章id
        up = Article.query.filter(Article.id > id).first()
        # 通过id 取 < id值 的第一个文章id
        down = Article.query.filter(Article.id < id).first()
        return render_template('web/info.html', content_id=content_id, article=article, articles=articles, up=up, down=down)

blog/templates/web/base_main.html
{% extends 'web/base.html' %}


{% block css %}
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
{% endblock %}

{% block js %}
<script src="/static/web/js/jquery-1.8.3.min.js"></script>
<script src="/static/web/js/comm.js"></script>
<script src="/static/web/js/modernizr.js"></script>

{% endblock %}


{% block header %}
<header id="header">
    <div class="navbox">
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <div class="logo"><a href="{{ url_for('web.blog_index') }}">-ONE PICE FTR- BLOG.</a></div>
        <nav>
            <ul id="starlist">
                <li><a href="{{ url_for('web.blog_index') }}">首页</a></li>
                <li><a href="{{ url_for('web.blog_diary') }}">个人博客日记</a></li>
                <!--<li class="menu"><a href="">博客网站制作</a>-->
                    <!--<ul class="sub">-->
                        <!--<li><a href="{{ url_for('web.blog_index') }}">推荐工具</a></li>-->
                        <!--<li><a href="{{ url_for('web.blog_index') }}">JS经典实例</a></li>-->
                        <!--<li><a href="{{ url_for('web.blog_index') }}">网站建设</a></li>-->
                        <!--<li><a href="{{ url_for('web.blog_index') }}">CSS3|Html5</a></li>-->
                        <!--<li><a href="{{ url_for('web.blog_index') }}">心得笔记</a></li>-->
                    <!--</ul>-->
                    <!--<span></span></li>-->
                <li><a href="{{ url_for('web.blog_good') }}">优秀个人博客</a></li>
                <!--<li><a href="{{ url_for('web.return_back') }}">添加文章</a></li>-->
                <li><a href="{{ url_for('web.blog_about') }}">关于我</a></li>
            </ul>
        </nav>
        <div class="searchico"></div>
    </div>
</header>
<div class="searchbox">
  <div class="search">
    <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
      <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
      <input name="show" value="title" type="hidden">
      <input name="tempid" value="1" type="hidden">
      <input name="tbname" value="news" type="hidden">
      <input name="Submit" class="input_submit" value="搜索" type="submit">
    </form>
  </div>
  <div class="searchclose"></div>
</div>
{% endblock %}


{% block footer %}
<footer>
  <div class="box">
    <div class="wxbox">
      <ul>
        <li><img src="/static/web/images/wx.jpg"><span>我的微信</span></li>
      </ul>
    </div>
    <div class="endnav">
      <p><b>站点声明：</b></p>
      <p>Copyright © <a href="" target="_blank">www.ONEPICE.FTR.com</a> All Rights Reserved. 备案号：<a href="" target="_blank">滇ICP备11002373号-1</a></p>
    </div>
  </div>
  <a href="#">
  <div class="top"></div>
  </a> </footer>
{% endblock %}

blog/templates/web/base_main1.html
{% extends 'web/base_main.html' %}

{% block content1 %}
        <!--<div class="whitebg notice">-->
        <!--<h2 class="htitle">网站公告</h2>-->
        <!--<ul>-->
        <!--<li><a href="/">十条设计原则教你学会如何设计网页布局!</a></li>-->
        <!--<li><a href="/">用js+css3来写一个手机栏目导航</a></li>-->
        <!--<li><a href="/">6条网页设计配色原则,让你秒变配色高手</a></li>-->
        <!--<li><a href="/">三步实现滚动条触动css动画效果</a></li>-->
        <!--</ul>-->
        <!--</div>-->
        <div class="whitebg paihang">
            <h2 class="htitle">点击排行</h2>
            <section class="topnews imgscale">
                <a href="{{ url_for('web.blog_diary') }}"><img src="/static/web/images/h1.jpg">
                    <span>海贼王
                        ONEPICE_FTR.</span>
                </a>
            </section>
            <ul>
                {% for article in articles %}
                    {% if article.id<=9 %}
                        <li><i></i><a href="{{ url_for('web.blog_content', id=article.id) }}">{{ article.title }}</a></li>
                    {% endif %}
                {% endfor %}
                <!---->
            </ul>
        </div>

        <!-- 图文信息 -->
        <!--<div class="ad whitebg imgscale">-->
            <!--<ul>-->
                <!--<a href="/"><img src="/static/web/images/ad02.jpg"></a>-->
            <!--</ul>-->
        <!--</div>-->

        <!--<div class="whitebg tuijian">-->
            <!--<h2 class="htitle">站长推荐</h2>-->
            <!--<section class="topnews imgscale">-->
                <!--<a href="/"><img src="/static/web/images/h2.jpg">-->
                    <!--<span>6条网页设计配色原则,让你秒变配色高手</span>-->
                <!--</a>-->
            <!--</section>-->
            <!--<ul>-->
                <!--<li><a href="/"><i><img src="/static/web/images/text01.jpg"></i>-->
                    <!--<p>十条设计原则教你学会如何设计网页布局!</p>-->
                <!--</a></li>-->
            <!--</ul>-->
        <!--</div>-->

        <!--图文信息-->
        <!--<div class="ad whitebg imgscale">-->
            <!--<ul>-->
                <!--<a href="/"><img src="/static/web/images/ad02.jpg"></a>-->
            <!--</ul>-->
        <!--</div>-->

        <div class="whitebg tongji">
            <h2 class="htitle">站点信息</h2>
            <ul>
                <li><b>建站时间</b>：2019-03-09</li>
                <li><b>文章统计</b>：0条</li>
                <li><b>文章评论</b>：0条</li>
                <li><b></b></li>
                <li><b>微信号</b>：扫描二维码，关注我</li>
                <img src="/static/web/images/wx.jpg" class="tongji_gzh">
                <li><b></b></li>
            </ul>
        </div>
    </div>
</article>
{% endblock %}

blog/templates/web/index.html
{% extends 'web/base_main1.html' %}

{% block title %}
    首页-FTR.
{% endblock %}


{% block content %}
<!--top end-->
<article>
    <!--lbox begin-->
    <div class="lbox">
        <!--banbox begin-->
        <div class="banbox">
            <div class="banner">
                <div id="banner" class="fader">
                    <li class="slide"><a href=""><!--target="_blank"--><img src="/static/web/images/banner.jpg"></a></li>
                    <li class="slide"><a href=""><!--target="_blank"--><img src="/static/web/images/home_slider.jpg"></a></li>
                    <li class="slide"><a href=""><!--target="_blank"--><img src="/static/web/images/3.jpg"></a></li>
                    <li class="slide"><a href=""><!--target="_blank"--><img src="/static/web/images/4.jpg"></a></li>
                    <div class="fader_controls">
                        <div class="page prev" data-target="prev"></div>
                        <div class="page next" data-target="next"></div>
                        <ul class="pager_list"></ul>
                    </div>
                </div>
            </div>
        </div>
        <!--banbox end-->
        <!--headline begin-->
        <div class="headline">
            <ul>
                <li><a href="" title="为什么说10月24日是程序员的节日？">
                    <img src="/static/web/images/h1.jpg"
                         alt="为什么说10月24日是程序员的节日？">
                    <span>为什么说10月24日是程序员的节日？</span></a>
                </li>
                <li><a href=""
                       title="个人网站做好了，百度不收录怎么办？来，看看他们怎么做的">
                    <img src="/static/web/images/h2.jpg" alt="个人网站做好了，百度不收录怎么办？来，看看他们怎么做的。">
                    <span>个人网站做好了，百度不收录怎么办？来，看看他们怎么做的。</span></a>
                </li>
            </ul>
        </div>
        <!--headline end-->
        <div class="clearblank"></div>
        <div class="tab_box whitebg">
            <div class="tab_buttons">
                <ul>
                    <li class="newscurrent">个人博客</li>
                    <!--<li>工作日记</li>-->
                </ul>
            </div>
            <div class="newstab">
                <div class="newsitem">
                    <div class="newspic">
                        <ul>
                            <li><a href=""><img src="/static/web/images/2.jpg">
                                <span>个人博客，属于我的小世界！</span></a>
                            </li>
                            <li><a href=""><img src="/static/web/images/4.jpg">
                                <span>个人网站做好了，百度不收录怎么办？来，看看他们怎么做的</span>
                            </a>
                            </li>
                        </ul>
                    </div>
                    <ul class="newslist">

                        {% for article in articles %}
                            {% if article.id<=5 %}
                            <li>
                                <i></i>
                                <a href="{{ url_for('web.blog_content', id=article.id) }}">{{ article.title }}</a>
                                <p>{{ article.desc }}</p>
                            </li>
                            {% endif %}
                        {% endfor %}

                    </ul>
                </div>
            </div>
        </div>
        <!--tab_box end-->
        <!--<div class="zhuanti whitebg">-->
        <!--&lt;!&ndash;<h2 class="htitle">&ndash;&gt;-->
        <!--&lt;!&ndash;<span class="hnav">&ndash;&gt;-->
        <!--&lt;!&ndash;<a href="/">原创模板</a>&ndash;&gt;-->
        <!--&lt;!&ndash;<a href="/">古典</a>&ndash;&gt;-->
        <!--&lt;!&ndash;<a href="/">清新</a>&ndash;&gt;-->
        <!--&lt;!&ndash;<a href="/">低调</a>&ndash;&gt;-->
        <!--&lt;!&ndash;</span>精彩专题&ndash;&gt;-->
        <!--&lt;!&ndash;</h2>&ndash;&gt;-->
        <!--&lt;!&ndash;<ul>&ndash;&gt;-->
        <!--&lt;!&ndash;<li><i class="ztpic">&ndash;&gt;-->
        <!--&lt;!&ndash;<a href="/" target="_blank">&ndash;&gt;-->
        <!--&lt;!&ndash;<img src="/static/web/images/1.jpg">&ndash;&gt;-->
        <!--&lt;!&ndash;</a>&ndash;&gt;-->
        <!--&lt;!&ndash;</i>&ndash;&gt;-->
        <!--&lt;!&ndash;<b>个人博客模板《今夕何夕》-响应式个人...</b>&ndash;&gt;-->
        <!--&lt;!&ndash;<span>&ndash;&gt;-->
        <!--&lt;!&ndash;个人博客模板《今夕何夕》，宽屏响应式个人博客模板，采用冷色系为主，固定导航栏和侧边栏，无缝滚动图片...&ndash;&gt;-->
        <!--&lt;!&ndash;</span>&ndash;&gt;-->
        <!--&lt;!&ndash;<a href="" target="_blank" class="readmore">文章阅读</a>&ndash;&gt;-->
        <!--&lt;!&ndash;</li>&ndash;&gt;-->
        <!--&lt;!&ndash;</ul>&ndash;&gt;-->
        <!--</div>-->
{% endblock %}


{% block article %}
        <div class="whitebg bloglist">
            <h2 class="htitle">最新博文</h2>
            <ul>
                <!--&lt;!&ndash;多图模式 置顶设计&ndash;&gt;-->
                <!--<li>-->
                <!--<h3 class="blogtitle"><a href="/" target="_blank"><b>【顶】</b>别让这些闹心的套路，毁了你的网页设计!</a></h3>-->
                <!--<span class="bplist">-->
                <!--<a href="/"><img src="/static/web/images/b02.jpg" alt=""></a>-->
                <!--<a href="/"><img src="/static/web/images/b03.jpg" alt=""></a>-->
                <!--<a href="/"><img src="static/web/images/b04.jpg" alt=""></a>-->
                <!--<a href="/"><img src="static/web/images/b05.jpg" alt=""></a>-->
                <!--</span>-->
                <!--<p class="blogtext">-->
                <!--如图，要实现上图效果，我采用如下方法：-->
                <!--1、首先在数据库模型，增加字段，分别是图片2，图片3。-->
                <!--2、增加标签模板，用if，else if来判断，输出。思路已打开，样式调用就可以多样化啦！...-->
                <!--</p>-->
                <!--<p class="bloginfo">-->
                <!--<i class="avatar"><img src="/static/web/images/avatar.jpg"></i>-->
                <!--<span>杨青青</span><span>2018-10-28</span><span>【<a href="/">原创模板</a>】</span>-->
                <!--</p>-->
                <!--</li>-->
                <!--&lt;!&ndash;单图&ndash;&gt;-->
                <!--<li>-->
                <!--<h3 class="blogtitle"><a href="/" target="_blank">【个人博客网站制作】自己不会个人博客网站制作，你会选择用什么博客程序源码？</a></h3>-->
                <!--<span class="blogpic imgscale">-->
                <!--<i><a href="/">原创模板</a></i>-->
                <!--<a href="/" title=""><img src="/static/web/images/b01.jpg" alt=""></a>-->
                <!--</span>-->
                <!--<p class="blogtext">-->
                <!--这些开源的博客程序源码，都是经过很多次版本测试的，都有固定的使用人群。我所知道的主流的博客程序有，Z-blog，Emlog，WordPress，Typecho等，免费的cms系统有，织梦cms（dedecms），phpcms，帝国cms（EmpireCMS）！... </p>-->
                <!--<p class="bloginfo">-->
                <!--<i class="avatar"><img src="/static/web/images/avatar.jpg"></i>-->
                <!--<span>杨青青</span><span>2018-10-28</span><span>【<a href="/">原创模板</a>】</span></p>-->
                <!--<a href="/" class="viewmore">阅读更多</a>-->
                <!--</li>-->

                <!--纯文字-->
                {% for article in articles %}
                <li>
                    <h3 class="blogtitle">
                        <a href="{{ url_for('web.blog_content', id=article.id) }}">
                            {{ article.title }}
                        </a>
                    </h3>
                    <p class="blogtext">{{ article.desc }}</p>
                    <p class="bloginfo">
                        <i class="avatar"><img src="/static/web/images/ftr.jpg"></i>
                        <span>ONEPICE_FTR.</span><span>{{ article.create_time }}</span><span>【<a>原创模板</a>】</span></p>
                    <a href="{{ url_for('web.blog_content', id=article.id) }}" class="viewmore">阅读全文</a>
                </li>
                {% endfor %}
                <!--</ul>-->
        </div>
        <!--bloglist end-->
    </div>
    {% endblock %}

    {% block content1 %}
    <div class="rbox">
        <div class="card">
            <h2>我的名片</h2>
            <p>网名：FTR_ONEPICE | 坐看云起时</p>
            <p>职业：Web前端设计师、网页设计</p>
            <p>现居：四川省-成都市</p>
            <p>Email：onepice_ftr@qq.com</p>
            <ul class="linkmore">
                <li><a href="" target="_blank" class="iconfont icon-zhuye" title="网站地址"></a></li>
                <li><a href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=wq2sp7KroaedpLawgrOz7KGtrw"
                       target="_blank" class="iconfont icon-youxiang" title="我的邮箱"></a></li>
                <li><a href="http://wpa.qq.com/msgrd?v=3&uin=550290027&site=qq&menu=yes" target="_blank"
                       class="iconfont icon---" title="QQ联系我"></a></li>
                <li id="weixin"><a href="#" target="_blank" class="iconfont icon-weixin" title="关注我的微信"></a><i><img
                        src="/static/web/images/wx.jpg"></i></li>
            </ul>
        </div>
        <!--<div class="whitebg notice">-->
        <!--<h2 class="htitle">网站公告</h2>-->
        <!--<ul>-->
        <!--<li><a href="/">十条设计原则教你学会如何设计网页布局!</a></li>-->
        <!--<li><a href="/">用js+css3来写一个手机栏目导航</a></li>-->
        <!--<li><a href="/">6条网页设计配色原则,让你秒变配色高手</a></li>-->
        <!--<li><a href="/">三步实现滚动条触动css动画效果</a></li>-->
        <!--</ul>-->
        <!--</div>-->
        <div class="whitebg paihang">
            <h2 class="htitle">点击排行</h2>
            <section class="topnews imgscale">
                <a href="{{ url_for('web.blog_diary') }}"><img src="/static/web/images/h1.jpg">
                    <span>海贼王
                        ONEPICE_FTR.</span>
                </a>
            </section>
            <ul>
                {% for article in articles %}
                    {% if article.id<=9 %}
                        <li><i></i><a href="{{ url_for('web.blog_content', id=article.id) }}">{{ article.title }}</a></li>
                    {% endif %}
                {% endfor %}
                <!---->
            </ul>
        </div>

        <!-- 图文信息 -->
        <!--<div class="ad whitebg imgscale">-->
            <!--<ul>-->
                <!--<a href="/"><img src="/static/web/images/ad02.jpg"></a>-->
            <!--</ul>-->
        <!--</div>-->

        <!--<div class="whitebg tuijian">-->
            <!--<h2 class="htitle">站长推荐</h2>-->
            <!--<section class="topnews imgscale">-->
                <!--<a href="/"><img src="/static/web/images/h2.jpg">-->
                    <!--<span>6条网页设计配色原则,让你秒变配色高手</span>-->
                <!--</a>-->
            <!--</section>-->
            <!--<ul>-->
                <!--<li><a href="/"><i><img src="/static/web/images/text01.jpg"></i>-->
                    <!--<p>十条设计原则教你学会如何设计网页布局!</p>-->
                <!--</a></li>-->
            <!--</ul>-->
        <!--</div>-->

        <!--图文信息-->
        <!--<div class="ad whitebg imgscale">-->
            <!--<ul>-->
                <!--<a href="/"><img src="/static/web/images/ad02.jpg"></a>-->
            <!--</ul>-->
        <!--</div>-->

        <div class="whitebg tongji">
            <h2 class="htitle">站点信息</h2>
            <ul>
                <li><b>建站时间</b>：2019-03-09</li>
                <li><b>文章统计</b>：0条</li>
                <li><b>文章评论</b>：0条</li>
                <li><b></b></li>
                <li><b>微信号</b>：扫描二维码，关注我</li>
                <img src="/static/web/images/wx.jpg" class="tongji_gzh">
                <li><b></b></li>
            </ul>
        </div>
    </div>
</article>
{% endblock %}

blog/templates/web/info.html
{% extends 'web/base_main.html' %}

{% block title %}
  文章内容-FTR.
{% endblock %}


{% block content %}
<!--top end-->
<article> 
  <!--lbox begin-->
  <div class="lbox">
    <div class="content_box whitebg">

      <h2 class="htitle">
        <span class="con_nav">
          您现在的位置是：<a href="{{ url_for('web.blog_index') }}">网站首页</a>>
          <a href="{{ url_for('web.blog_diary') }}">个人博客日记</a>
        </span>个人博客模板
      </h2>

      <h1 class="con_tilte">{{ content_id.title }}</h1>
      <p class="bloginfo">
        <i class="avatar"><img src="/static/web/images/ftr.jpg"></i>
        <span>FTR.</span><span>{{ content_id.create_time }}</span><span>【<a>程序人生</a>】</span>
        <span>109990人已围观</span>
      </p>
      <p class="con_info">
        <b>简介</b>
        个人博客，用来做什么？我刚开始就把它当做一个我吐槽心情的地方，也就相当于一个
        网络记事本， 写上一些关于自己生活工作中的小情小事，也会放上一些照片，音乐。每
        天工作回家后就能访问自己的网站，一边听着音乐，一边写写文章。
      </p>

      <div class="con_text">
        <p>{{ content_id.content }}</p>
        <p class="share">
          <b>转载：</b>
          感谢您对FTR.个人博客网站平台的支持。
        </p>
        <!--<p><span class="diggit">很赞哦！ (74)</span></p>-->
        <div class="nextinfo">
            {% if down %}
          <p>上一篇：<a href="{{ url_for('web.blog_content', id=down.id) }}">{{ down.title }}</a></p>
            {% endif %}
            {% if up %}
          <p>下一篇：<a href="{{ url_for('web.blog_content', id=up.id) }}">{{ up.title }}</a></p>
            {% endif %}

        </div>
      </div>
    </div>

    <!--<div class="whitebg">-->
      <!--<h2 class="htitle">相关文章</h2>-->
      <!--<ul class="otherlink">-->
        <!--<li><a href="/download/div/2018-04-22/815.html" title="html5个人博客模板《黑色格调》">html5个人博客模板《黑色格调》</a></li>-->
        <!--<li><a href="/download/div/2018-04-18/814.html" title="html5个人博客模板主题《清雅》">html5个人博客模板主题《清雅》</a></li>-->
        <!--<li><a href="/download/div/2018-03-18/807.html" title="html5个人博客模板《绅士》">html5个人博客模板《绅士》</a></li>-->
        <!--<li><a href="/download/div/2018-02-22/798.html" title="html5时尚个人博客模板-技术门户型">html5时尚个人博客模板-技术门户型</a></li>-->
        <!--<li><a href="/download/div/2017-09-08/789.html" title="html5个人博客模板主题《心蓝时间轴》">html5个人博客模板主题《心蓝时间轴》</a></li>-->
        <!--<li><a href="/download/div/2017-07-16/785.html" title="古典个人博客模板《江南墨卷》">古典个人博客模板《江南墨卷》</a></li>-->
        <!--<li><a href="/download/div/2017-07-13/783.html" title="古典风格-个人博客模板">古典风格-个人博客模板</a></li>-->
        <!--<li><a href="/download/div/2015-06-28/748.html" title="个人博客《草根寻梦》—手机版模板">个人博客《草根寻梦》—手机版模板</a></li>-->
        <!--<li><a href="/download/div/2015-04-10/746.html" title="【活动作品】柠檬绿兔小白个人博客模板">【活动作品】柠檬绿兔小白个人博客模板</a></li>-->
        <!--<li><a href="/jstt/bj/2015-01-09/740.html" title="【匆匆那些年】总结个人博客经历的这四年…">【匆匆那些年】总结个人博客经历的这四年…</a></li>-->
      <!--</ul>-->
    <!--</div>-->

    <!--<div class="whitebg gbook">-->
      <!--<h2 class="htitle">文章评论</h2>-->
      <!--<ul>-->
      <!--</ul>-->
    <!--</div>-->
  </div>
  <!--lbox end-->
  <div class="rbox">
        <div class="whitebg paihang">
            <h2 class="htitle">点击排行</h2>
            <section class="topnews imgscale">
                <a href=""><img src="/static/web/images/h1.jpg">
                    <span>海贼王
                        ONEPICE_FTR.</span>
                </a>
            </section>
            <ul>
                {% for article in articles %}
                    {% if article.id<=9 %}
                        <li><i></i><a href="{{ url_for('web.blog_content', id=article.id) }}">{{ article.title }}</a></li>
                    {% endif %}
                {% endfor %}
                <!---->
            </ul>
        </div>

    <!--<div class="whitebg tuijian">-->
      <!--<h2 class="htitle">本栏推荐</h2>-->
      <!--<section class="topnews imgscale">-->
        <!--<a href="/">-->
          <!--<img src="/static/web/images/h2.jpg">-->
          <!--<span>6条网页设计配色原则,让你秒变配色高手</span></a>-->
      <!--</section>-->
      <!--<ul>-->
        <!--<li><a href="/"><i><img src="/static/web/images/text01.jpg"></i>-->
          <!--<p>十条设计原则教你学会如何设计网页布局!</p>-->
          <!--</a></li>-->
      <!--</ul>-->
    <!--</div>-->
    <!--<div class="ad whitebg imgscale">-->
      <!--<ul>-->
        <!--<a href="/"><img src="/static/web/images/ad.jpg"></a>-->
      <!--</ul>-->
    <!--</div>-->
    <div class="whitebg cloud">
      <h2 class="htitle">标签云</h2>
      <ul>
        {% for article in article %}
            <a href="">{{ article.t_name }}</a>
        {% endfor %}
      </ul>
    </div>
    <!--<div class="whitebg wenzi">-->
      <!--<h2 class="htitle">猜你喜欢</h2>-->
      <!--<ul>-->
        <!--<li><a href="/">十条设计原则教你学会如何设计网页布局!</a></li>-->
        <!--&lt;!&ndash;<li><a href="/">用js+css3来写一个手机栏目导航</a></li>&ndash;&gt;-->
        <!--&lt;!&ndash;<li><a href="/">6条网页设计配色原则,让你秒变配色高手</a></li>&ndash;&gt;-->
        <!--&lt;!&ndash;<li><a href="/">三步实现滚动条触动css动画效果</a></li>&ndash;&gt;-->
        <!--&lt;!&ndash;<li><a href="/">个人博客，属于我的小世界！</a></li>&ndash;&gt;-->
        <!--&lt;!&ndash;<li><a href="/">安静地做一个爱设计的女子</a></li>&ndash;&gt;-->
        <!--&lt;!&ndash;<li><a href="/">个人网站做好了，百度不收录怎么办？来，看看他们怎么做的。</a></li>&ndash;&gt;-->
        <!--&lt;!&ndash;<li><a href="/">做个人博客如何用帝国cms美化留言增加头像选择</a></li>&ndash;&gt;-->
      <!--</ul>-->
    <!--</div>-->
    <!--<div class="ad whitebg imgscale">-->
      <!--<ul>-->
        <!--<a href="/"><img src="/static/web/images/ad02.jpg"></a>-->
      <!--</ul>-->
    <!--</div>-->
    <div class="whitebg tongji">
        <h2 class="htitle">站点信息</h2>
        <ul>
           <li><b>建站时间</b>：2019-03-09</li>
           <li><b>文章统计</b>：0条</li>
           <li><b>文章评论</b>：0条</li>
           <li><b></b></li>
           <li><b>微信号</b>：扫描二维码，关注我</li>
           <img src="/static/web/images/wx.jpg" class="tongji_gzh">
           <li><b></b></li>
      </ul>
    </div>
  </div>
</article>
{% endblock %}