blog/back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    u_name = db.Column(db.String(10), unique=True, nullable=False)
    u_password = db.Column(db.String(255), nullable=False)
    is_delete = db.Column(db.Boolean, default=0)
    create_time = db.Column(db.DateTime, default=datetime.now)

    def save(self):
        db.session.add(self)
        db.session.commit()


# 分类表
class ArticleType(db.Model):
    __tablename__ = 'art_type'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    t_name = db.Column(db.String(10), unique=True, nullable=False)
    arts = db.relationship('Article', backref='tp')


# 文章表
class Article(db.Model):
    __tablename__ = 'article'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    # 文章名称
    title = db.Column(db.String(30), unique=True, nullable=False)
    # 文章描述
    desc = db.Column(db.String(100), nullable=False)
    # 文章内容
    content = db.Column(db.Text, nullable=False)
    # 创建文章时间
    create_time = db.Column(db.DateTime, default=datetime.now)
    type = db.Column(db.Integer, db.ForeignKey('art_type.id'))

blog/back/views.py
from flask import request, render_template, Blueprint, redirect, url_for, session
# 编码解码
from werkzeug.security import generate_password_hash, check_password_hash
from back.models import db, User, Article, ArticleType
from utils.functions import is_login

back_blue = Blueprint('back', __name__)


# 登录主页
@back_blue.route('/index/')
@is_login
def admin_index():
    return render_template('back/index.html')


# 注册账号
@back_blue.route('/register/', methods=['GET', 'POST'])
def admin_register():
    if request.method == 'GET':
        return render_template('back/register.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        im_login = request.form.get('im_login')
        if im_login:
            return redirect(url_for('back.admin_login'))
        # 判断参数是否全部输入
        if username and password and password2:
            # 判断账号是否注册
            user = User.query.filter(User.u_name == username).first()
            if user:
                error = '该账号已注册，请重新输入！'
                return render_template('back/register.html', error=error)
            else:
                # 判断密码是否一致
                if password == password2:
                    admin = User()
                    admin.u_name = username
                    admin.u_password = generate_password_hash(password)
                    admin.u_password2 = password2
                    admin.save()
                    return redirect(url_for('back.admin_login'))
                else:
                    error = '密码不一致！'
                    return render_template('back/register.html', error=error)
        else:
            error = '确保信息输入完整'
            return render_template('back/register.html', error=error)


# 登录账号
@back_blue.route('/login/', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'GET':
        return render_template('back/login.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        if username and password:
            np_name = User.query.filter(User.u_name == username).first()
            if not np_name:
                error = '该账号未注册！'
                return render_template('back/login.html', error=error)
            if not check_password_hash(np_name.u_password, password):
                error = '密码错误！请重新输入！'
                return render_template('back/login.html', error=error)
            session['user_id'] = np_name.id
            return redirect(url_for('back.admin_index'))

        else:
            error = '请填写完整信息！'
            return render_template('back/login.html', error=error)


# 注销帐号
@back_blue.route('/logout/', methods=['GET'])
@is_login
def logout():
    del session['user_id']
    return redirect(url_for('back.admin_login'))


# 文章分类
@back_blue.route('/a_type/', methods=['GET', 'POST'])
def a_type():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/category_list.html', types=types)


# 添加文章分类
@back_blue.route('/add_type/', methods=['GET', 'POST'])
def add_type():
    if request.method == 'GET':
        return render_template('back/category_add.html')
    if request.method == 'POST':
        atype = request.form.get('atype')
        if atype:
            # 保存分类信息
            art_type = ArticleType()
            art_type.t_name = atype
            db.session.add(art_type)
            db.session.commit()
            return redirect(url_for('back.a_type'))
        else:
            error = '请填写分类信息'
            return render_template('back/category_add.html', error=error)


# 删除分类功能
@back_blue.route('/del_type/<int:id>', methods=['GET'])
def del_type(id):
    atype = ArticleType.query.get(id)
    db.session.delete(atype)
    db.session.commit()
    return redirect(url_for('back.a_type'))


# 文章列表
@back_blue.route('/article_list/', methods=['GET'])
def article_list():
    articles = Article.query.all()
    return render_template('back/article_list.html', articles=articles)


# 添加文章
@back_blue.route('/article_add/', methods=['GET', 'POST'])
def article_add():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/article_detail.html', types=types)
    if request.method == 'POST':
        title = request.form.get('name')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')
        if title and desc and category and content:
            # 保存
            art = Article()
            art.title = title
            art.desc = desc
            art.content = content
            art.type = category
            db.session.add(art)
            db.session.commit()
            return redirect(url_for('back.article_list'))
        else:
            error = '请填写完整的文章信息'
            return render_template('back/article_detail.html', error=error)


# 删除文章
@back_blue.route('/article_del/<int:id>/', methods=['GET'])
def article_del(id):
    article = Article.query.get(id)
    db.session.delete(article)
    db.session.commit()
    return redirect(url_for('back.article_list'))


# 用户信息
@back_blue.route('/user_list/', methods=['GET'])
def user_list():
    users = User.query.all()
    return render_template('back/user_list.html', users=users)


# 用户删除
@back_blue.route('/user_del/<int:id>', methods=['GET'])
def user_del(id):
    users = User.query.get(id)
    db.session.delete(users)
    db.session.commit()
    return redirect(url_for('back.user_list'))


# 添加新用户
@back_blue.route('/user_add/', methods=['GET', 'POST'])
def users_add():
    if request.method == 'GET':
        return render_template('back/goods_detail.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        # 判断参数是否全部输入
        if username and password and password2:
            # 判断账号是否注册
            user = User.query.filter(User.u_name == username).first()
            if user:
                error = '该账号已注册，请重新输入！'
                return render_template('back/goods_detail.html', error=error)
            else:
                # 判断密码是否一致
                if password == password2:
                    admin = User()
                    admin.u_name = username
                    admin.u_password = generate_password_hash(password)
                    admin.u_password2 = password2
                    admin.save()
                    return redirect(url_for('back.user_list'))
                else:
                    error = '密码不一致！'
                    return render_template('back/goods_detail.html', error=error)
        else:
            error = '确保信息输入完整'
            return render_template('back/goods_detail.html', error=error)

blog/web/views.py
from flask import request, render_template, Blueprint, redirect, url_for

# 编码解码
from back.models import Article, ArticleType

web_blue = Blueprint('web', __name__)


# 跳转主页
@web_blue.route('/', methods=['GET'])
def blog():
    return render_template('web/index.html')


# 主页
@web_blue.route('/blog_index/', methods=['GET', 'POST'])
def blog_index():
    articles = Article.query.limit(10).all()
    return render_template('web/index.html', articles=articles)


# 博客日记
@web_blue.route('/blog_diary/', methods=['GET', 'POST'])
def blog_diary():
    article = ArticleType.query.limit(10).all()
    articles = Article.query.limit(10).all()
    return render_template('web/list.html', article=article, articles=articles)


# 优秀个人博客
@web_blue.route('/blog_good/', methods=['GET', 'POST'])
def blog_good():
    if request.method == 'GET':
        return render_template('web/daohang.html')


# 关于我
@web_blue.route('/blog_about/', methods=['GET', 'POST'])
def blog_about():
    if request.method == 'GET':
        return render_template('web/about.html')


# 添加文章
@web_blue.route('/return_back/', methods=['GET', 'POST'])
def return_back():
    return redirect(url_for('back.admin_login'))


# 内容
@web_blue.route('/blog_content/<int:id>/', methods=['GET', 'POST'])
def blog_content(id):
    if request.method == 'GET':
        # 标签云 取标签id
        article = ArticleType.query.limit(10).all()
        # 通过标签 取对应id文章内容
        content_id = Article.query.filter_by(id=id).first()
        # 点击排名 文章显示
        articles = Article.query.limit(10).all()
        # 通过id 取 > id值 的第一个文章id
        up = Article.query.filter(Article.id > id).first()
        # 通过id 取 < id值 的第一个文章id
        down = Article.query.filter(Article.id < id).first()
        return render_template('web/info.html', content_id=content_id, article=article, articles=articles, up=up, down=down)

blog/templates/back/article_detail.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章添加
{% endblock %}

{% block js %}
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id');
        });
    </script>
{% endblock %}

{% block content %}
<section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章详情</h2>
            <a class="fr top_rt_btn" href="{{ url_for('back.article_list') }}">返回文章列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {{ error }}
            <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">文章名称：</span>
                        <input type="text" name="name" value="" class="textbox textbox_295" placeholder="文章名称..."/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">文章描述：</span>
                        <input type="text" name="desc" value=""  class="textbox" placeholder="文章描述..."/>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">分类：</span>
                        <select class="select" name="category">
                            {% for type in types %}
                            <option value="{{ type.id }}">{{ type.t_name }}</option>
                            {% endfor %}
                        </select>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">文章描述：</span>
                        <!--<textarea name="content"></textarea>-->
                        <!--<textarea id="editor_id" name="content" style="width:700px;height:300px;">-->
                            <!--&lt;strong&gt;HTML内容&lt;/strong&gt;-->
                        <!--</textarea>-->
                        <input type="text" name="content" value="" class="textbox textbox_295" placeholder="文章内容..."/>
                    </li>
                    <li>
                        <!--<span class="item_name" style="width:120px;">插入图片：</span>-->
                        <!--<input type="image" name="content" value="" class="textbox textbox_295" placeholder="插入图片..."/>-->
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

blog/templates/back/article_list.html
{% extends 'back/base_main.html' %}

{% block title %}

{% endblock %}


{% block content %}
<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章列表</h2>
            <a href="{{url_for('back.article_add')}}" class="fr top_rt_btn add_icon">添加文章</a>
        </div>
        <table class="table">
            <tr>
                <th>文章标题</th>
                <th>文章分类</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
            {% for article in articles %}
                <tr>
                    <td class="center">{{ article.title }}</td>
                    <td class="center">{{ article.tp.t_name }}</td>
                    <td class="center">
                        {{ article.create_time }}
                    </td>
                    <td class="center">
                        <a href="{{ url_for('back.article_del', id=article.id) }}" onclick="" title="删除" class="link_icon">&#100;</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <!--<aside class="paging">-->
            <!--<a>当前1页</a>-->
            <!--<a href="">第一页</a>-->
            <!---->
                <!--<a href=""> 1 </a>-->
            <!---->
                <!--<a href=""> 2 </a>-->
            <!---->
                <!--<a href=""> 3 </a>-->
            <!---->
            <!--<a href="">最后一页</a>-->
        <!--</aside>-->
    </div>
</section>
{% endblock %}

blog/templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="DeathGhost"/>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}

</head>
<body>
    {% block header %}
    {% endblock %}
    {% block aside %}
    {% endblock %}
    {% block content %}
    {% endblock %}
</body>
</html>

blog/templates/back/base_main.html
{% extends 'back/base.html' %}

{% block title %}
{% endblock %}



{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/back/css/style.css"/>
{% endblock %}


{% block js %}
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="/static/back/js/jquery.js"></script>
    <script src="/static/back/js/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock %}


{% block header %}
    <header>
        <h1><img src="/static/back/images/admin_logo.png"/></h1>
        <ul class="rt_nav">
            <li><a href="{{ url_for('web.blog_index') }}" target="_blank" class="website_icon">站点首页</a></li>
            <li><a href="#" class="set_icon">账号设置</a></li>
            <li><a href="{{ url_for('back.logout') }}" class="quit_icon">安全退出</a></li>
        </ul>
    </header>
{% endblock %}


{% block aside %}
    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">博客后台菜单栏</a></h2>
        <ul>
            <li>
                <dl>
                    <dt>文章管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="{{url_for('back.a_type')}}">文章分类</a></dd>
                    <dd><a href="{{url_for('back.article_list')}}">文章列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="{{ url_for('back.user_list') }}">用户信息</a></dd>
                </dl>
            </li>
        </ul>
    </aside>
{% endblock %}


{% block content %}
{% endblock %}

blog/templates/back/base_main2.html
{% extends 'back/base.html' %}

{% block title %}
{% endblock %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/back/css/style.css"/>
        <style>
            body{height:100%;background:#16a085;overflow:hidden;}
            canvas{z-index:-1;position:absolute;}
        </style>
{% endblock %}


{% block js %}
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="/static/back/js/jquery.js"></script>
    <script src="/static/back/js/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock %}



{% block content %}
{% endblock %}

blog/templates/back/category_add.html
{% extends 'back/base_main.html' %}

{% block title %}
    添加分类
{% endblock %}

{% block content %}
<section class="rt_wrap mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章分类详情</h2>
            <a class="fr top_rt_btn" href="{{ url_for('back.a_type') }}">返回分类列表</a>
        </div>
        <form action="" method="post">
            {{ error }}
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">文章分类名称：</span>
                        <input type="text" name="atype">
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="text" name="atype">
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

blog/templates/back/category_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章分类
{% endblock %}
{% block content %}
<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章分类列表</h2>
            <a href="{{url_for('back.add_type')}}" class="fr top_rt_btn add_icon">添加文章分类</a>
        </div>
        <table class="table">
            <tr>
                <th>类型</th>
                <th>操作</th>
            </tr>
        {% for type in types %}
            <tr>
                <td class="center">
                    {{ type.t_name }}
                </td>
                <td class="center">
                    <a href="{{ url_for('back.del_type', id=type.id) }}" title="删除" class="link_icon">&#101;</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</section>
{% endblock %}

blog/templates/back/goods_desc.html
{% extends 'back/base_main.html' %}

{% block js %}
    {{ super() }}
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
        });
    </script>
{% endblock %}

{% block content %}
    <section class="rt_wrap">

        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">商品详情</h2>
                <a class="fr top_rt_btn" href="">返回商品列表</a>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                <input type='hidden' name='csrfmiddlewaretoken' value='QuPi2QUuEhlKchGijsQULGJKUZO6bOJacZPtDzGnIfWv89lLhtnbVM2EVRxtAXCJ' />
                <section>
                    <ul class="ulColumn2">
                        <li>
                            <span class="item_name" style="width:120px;">产品详情：</span>
                            <label style="display:inline-block;padding:15px;background:#f8f8f8;">
                                <textarea id="editor_id" name="content" style="width:700px;"></textarea>
                            </label>
                        </li>
                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
    </section>
{% endblock %}

blog/templates/back/goods_detail.html
{% extends 'back/base_main.html' %}


{% block js %}
    {{ super() }}
        <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
        <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
        <script type="text/javascript">
            KindEditor.ready(function(K) {
                    window.editor = K.create('#editor_id');
            });
        </script>
{% endblock %}


{% block content %}
<section class="rt_wrap mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">用户详情</h2>
            <a class="fr top_rt_btn" href="{{ url_for('back.user_list') }}">返回用户列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
            <section>
                <p style="color:red">{{ error }}</p>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">用户账号：</span>
                        <input type="text" name="username" value="" class="textbox textbox_295" placeholder="用户账号..."/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">用户密码：</span>
                        <input type="text" name="password" value=""  class="textbox" placeholder="用户密码..."/>
                        
                    </li>

                    <li>
                        <span class="item_name" style="width:120px;">确认密码：</span>
                        <input type="text" name="password2" value="" class="textbox textbox_295" placeholder="再次输入密码..."/>

                    </li>

                    <!--<li>-->
                        <!--<span class="item_name" style="width:120px;">上传商品首图：</span>-->
                        <!---->
                        <!--<label class="uploadImg">-->
                             <!--<input type="file" name="goods_front_image"/>-->
                             <!--<span>上传图片</span>-->
                        <!--</label>-->
                    <!--</li>-->
                    <!--<li>-->
                        <!--<span class="item_name" style="width:120px;">产品详情：</span>-->

                        <!--<textarea id="editor_id" name="content" style="width:700px;height:300px;">-->
                            <!--&lt;strong&gt;HTML内容&lt;/strong&gt;-->
                        <!--</textarea>-->
                    <!--</li>-->
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

blog/templates/back/index.html
{% extends 'back/base_main.html' %}

{% block title %}
    后台管理系统--首页
{% endblock %}


{% block js %}
    {{ super() }}
    <script src="../static/js/html5.js"></script>
    <script>
        (function($){
            $(window).load(function(){

                $("a[rel='load-content']").click(function(e){
                    e.preventDefault();
                    var url=$(this).attr("href");
                    $.get(url,function(data){
                        $(".content .mCSB_container").append(data); //load new content inside .mCSB_container
                        //scroll-to appended content
                        $(".content").mCustomScrollbar("scrollTo","h2:last");
                    });
                });

                $(".content").delegate("a[href='top']","click",function(e){
                    e.preventDefault();
                    $(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
                });
            });
        })(jQuery);
    </script>
{% endblock %}


{% block content %}
<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
            博客管理后台
        </h1>
        <br>
        <p>博客管理采用Flask开发，存储数据库为关系型数据库Mysql</p>
        <br>
        <p>后台集中功能为：文章发布、用户管理</p>
    </div>
</section>
{% endblock %}

blog/templates/back/login.html
{% extends 'back/base_main2.html' %}

{% block title %}
    后台登录
{% endblock %}


{% block js %}
    {{ super() }}
    <script src="/static/back/js/verificationNumbers.js"></script>
    <script src="/static/back/js/Particleground.js"></script>
    <script>
        $(document).ready(function() {
          //粒子背景特效
          $('body').particleground({
            dotColor: '#5cbdaa',
            lineColor: '#5cbdaa'
          });
          //验证码
          createCode();
          //测试提交，对接程序删除即可
          $(".submit_btn").click(function(){
              location.href="index.html";
              });
        });
    </script>
{% endblock %}

{% block content %}
<form action="" method="post">
    <dl class="admin_login">
        <dt>
            <strong>博客后台管理系统</strong>
            <em>Management System</em>
        </dt>

        <dd class="user_icon">
            <input name="username" type="text" placeholder="账号" class="login_txtbx"/>
        </dd>
        <dd class="pwd_icon">
            <input name="password" type="password" placeholder="密码" class="login_txtbx"/>
        </dd>
        {{ error }}
        <dd>
            <input type="submit" value="立即登录" class="submit_btn"/>
        </dd>
        <!--<dd>-->
            <!--<input name="im_register" type="submit" value="点击注册" class="submit_btn"/>-->
        <!--</dd>-->
        <dd>

            <p>{{ '© 1997-2027 Ftr.鸱夷 版权所有' | safe }}</p>
            <p>{{ '滇C9-19970909-9' | safe }}</p>
        </dd>
    </dl>
</form>
{% endblock %}

blog/templates/back/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>

    </title>

    <link rel="stylesheet" type="text/css" href="css/style.css">

    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

</head>
<body>


<header>
    <h1><img src="images/admin_logo.png"/></h1>
    <ul class="rt_nav">
        <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="#" class="set_icon">账号设置</a></li>
        <li><a href="login.html" class="quit_icon">安全退出</a></li>
    </ul>
</header>




    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">商城后台菜单栏</a></h2>
        <ul>
            <li>
                <dl>
                    <dt>商品管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="goods_category_detail.html">商品分类</a></dd>
                    <dd><a href="goods_list.html">商品列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单管理</dt>
                    <dd><a href="order_list.html">订单列表</a></dd>
                </dl>
            </li>
            <li>    
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="user_list.html">用户列表</a></dd>
                </dl>
            </li>
            </ul>
    </aside>

    <style>
    .dataStatistic{width:400px;height:200px;border:1px solid #ccc;margin:0 auto;margin:10px;overflow:hidden}
    #cylindrical{width:400px;height:200px;margin-top:-15px}
    #line{width:400px;height:200px;margin-top:-15px}
    #pie{width:400px;height:200px;margin-top:-15px}
    </style>




<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">订单列表</h2>
        </div>
        <table class="table">
            <tr>
                <th>订单编号</th>
                <th>收件人</th>
                <th>联系电话</th>
                <th>收件人地址</th>
                <th>订单金额</th>
                <th>配送方式</th>
                <!--<th>操作</th>-->
            </tr>
            
                <tr>
                    <td class="center">Pg5Wq4GYKWge6fhMDiMI</td>
                    <td>小花</td>
                    <td>12887754321</td>
                    <td>
                        <address>四川省成都市</address>
                    </td>
                    <td class="center"><strong class="rmb_icon">1260.0</strong></td>
                    <td class="center">申通快递</td>
                    <!--<td class="center">-->
                        <!--<a href="#" title="查看订单" class="link_icon" target="_blank">&#118;</a>-->
                    <!--</td>-->
                </tr>
        </table>
        <aside class="paging">
            <a>当前1页</a>
            <a href="">第一页</a>
            
                <a href=""> 1 </a>
                <a href=""> 2 </a>
                <a href=""> 3 </a>
                <a href=""> 4 </a>
            
            <a href="">最后一页</a>
        </aside>
    </div>
</section>



</body>
</html>

blog/templates/back/user_list.html
{% extends 'back/base_main.html' %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">用户列表</h2>
       <a href="{{ url_for('back.users_add') }}" class="fr top_rt_btn add_icon">添加新用户</a>
      </div>
      <table class="table">
       <tr>
        <th>用户账号</th>
        <th>用户密码</th>
        <th>操作</th>
       </tr>
       {% for user in users %}
       <tr>
        <td class="center">{{ user.u_name }}</td>
        <!--overflow: hidden;/*内容超出后隐藏*/-->
        <!--text-overflow: ellipsis;/* 超出内容显示为省略号*/-->
        <!--white-space: nowrap;/*文本不进行换行*/-->
        <td class="center" style="overflow:hidden">{{ user.u_password }}</td>
        <td class="center">
         <!--<a href="user_detail.html" title="编辑" class="link_icon">&#101;</a>-->
         <a href="{{ url_for('back.user_del', id=user.id) }}" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
       {% endfor %}
      </table>
      <!--<aside class="paging">-->
       <!--<a>第一页</a>-->
       <!--<a>1</a>-->
       <!--<a>2</a>-->
       <!--<a>3</a>-->
       <!--<a>…</a>-->
       <!--<a>1004</a>-->
       <!--<a>最后一页</a>-->
      <!--</aside>-->
 </div>
</section>
{% endblock %}